# Generated by Django 4.2 on 2023-04-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.ManyToManyField(related_name='products', to='goods.stock'),
        ),
    ]
