# Generated by Django 4.2 on 2023-04-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_product_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.BigIntegerField(),
        ),
    ]
