# Generated by Django 4.2 on 2023-04-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_positions', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockProductReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.product')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.reserve')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.stock')),
            ],
        ),
    ]
